version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Add env
          command: |
            echo "BASE_URL=$BASE_URL" > .env
            echo "AVATAR_URL=$AVATAR_URL" >> .env
            echo "MAINTENANCE=$MAINTENANCE" >> .env
      - restore_cache:
          name: Restore yarn dependencies
          keys:
            - v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Step
          command: yarn install
      - save_cache:
          name: Save Cache of yarn dependencies
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            # - ~/node_modules
      - run:
          name: Build Step
          command: NODE_ENV=production yarn generate
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          from: dist
          to: 's3://enqueter-front'
          overwrite: true
        # Disable cache before ttl, and delete the cache.
      - run: aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master