export default interface UserStats {
  id: Number,
  user_id: Number,
  total_rank_point: Number,
  total_point: Number,
  month_rank_point: Number,
  month_point: Number,
  week_rank_point: Number,
  week_point: Number,
  total_rank_response: Number,
  total_response: Number,
  month_rank_response: Number,
  month_response: Number,
  week_rank_response: Number,
  week_response: Number,
  total_questions: Number,
  week_questions: Number,
  month_questions: Number,
  total_answers: Number,
  week_answers: Number,
  month_answers: Number,
}